AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  gitlab-to-slack

  Sample SAM Template for gitlab-to-slack

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  GitlabToSlackFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: functions/
      Handler: app.lambda_handler
      Runtime: ruby2.7
      Architectures:
        - x86_64
      Environment:
        Variables:
          SLACK_WEBHOOK_URL: https://hooks.slack.com/services/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
          GITLAB_MR_EVENTS_SUBSCRIBED: "open,update"
      Events:
        GitlabToSlack:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /
            Method: POST

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  GitlabToSlackApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/webhook/"
  GitlabToSlackARN:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt GitlabToSlackFunction.Arn
  GitlabToSlackARNIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt GitlabToSlackFunctionRole.Arn
